### ISSUE TITLE
Can't build for device 

### ISSUE THREAD

**Issue by ptsequeira** [hansemannn/titanium-context-menu#2]
Hi,

When trying to build to device, the build fails. In simulator it runs without a problem.

`ld: warning: directory not found for option '-L/Users/ptiagosequeira/Documents/projects/personal/xServer/build/iphone/lib'
[TRACE]  ld: warning: object file (/Users/ptiagosequeira/Documents/projects/personal/xServer/build/iphone/build/Products/Debug-iphoneos/libti.contextmenu.a(TiContextmenuModule.o)) was built for newer iOS version (11.0) than being linked (10.0)
[TRACE]  ld: warning: object file (/Users/ptiagosequeira/Documents/projects/personal/xServer/build/iphone/build/Products/Debug-iphoneos/libti.contextmenu.a(TiContextmenuModuleAssets.o)) was built for newer iOS version (11.0) than being linked (10.0)
[TRACE]  ld: warning: object file (/Users/ptiagosequeira/Documents/projects/personal/xServer/build/iphone/build/Products/Debug-iphoneos/libti.contextmenu.a(TiViewProxy+ContextMenu.o)) was built for newer iOS version (11.0) than being linked (10.0)
[TRACE]  ld: warning: object file (/Users/ptiagosequeira/Documents/projects/personal/xServer/build/iphone/build/Products/Debug-iphoneos/libti.contextmenu.a(TiUIButtonProxy+ContextMenu.o)) was built for newer iOS version (11.0) than being linked (10.0)
[TRACE]  Undefined symbols for architecture arm64:
[TRACE]    "_OBJC_CLASS_$_TiUIButtonProxy", referenced from:
[TRACE]        __OBJC_$_CATEGORY_TiUIButtonProxy_$_ContextMenu in libti.contextmenu.a(TiUIButtonProxy+ContextMenu.o)
[TRACE]  ld: symbol(s) not found for architecture arm64
[TRACE]  clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by hansemannn** [comment]
The module requires iOS 11+
