### ISSUE TITLE
SystemButtons are invisible

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-context-menu#3]
With changing my version from 2.0.0 to 2.2.0, all systemButtons are invisible. They are clickable, but not visible. In my case, the system buttons are in the `RightNavButtons` tag and I even don't use the context menu there

Example
```
<RightNavButtons platform="ios">
			<Button id="addBtn" systemButton="ADD" onClick="handleAdd" enabled="false" /> 
			<Button id="feedbackBtn" onClick="handleFeedbackBtn" image="images/feedback.png" /> 
		</RightNavButtons>
```

**Comment by hansemannn** [comment]
Yeah, we override all nav buttons right now. I'll try to fix that later this week!

**Comment by caspahouzer** [comment]
When this is fixed, this module is really awesome and so easy to use

**Comment by hansemannn** [comment]
Fixed in https://github.com/hansemannn/titanium-context-menu/releases/tag/v2.2.1 !

**Comment by caspahouzer** [comment]
Works perfect! Thank you
