### ISSUE TITLE
ListView menu is missing identifier

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-context-menu#4]
When I'm using the menu on listviews, I have the actionIndex, but the identifier is missing.

How can I achieve that?

**Comment by hansemannn** [comment]
It's currently not handled, sorry

**Comment by caspahouzer** [comment]
I can solve it via the `actionIndex`

I would let this issue opened for a coming version, if it's okay for you

**Comment by hansemannn** [comment]
We now support the `identifier` in each click event!
